site_name:           SemiparametricAUC.jl
repo_url:            https://github.com/sbohora/SemiparametricAUC.jl
site_description:    Perform semiparametric AUC in Julia with discrete covariates
site_author:         Som B. Bohora

theme:               readthedocs

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math # For LaTeX

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Introduction: index.md
